// ── ข้อมูลรายหมู่บ้านเพิ่มเติมจาก Excel ลุ่มน้ำสาละวิน ──
// เพิ่มฟิลด์: sub_basin_code, sub_basin_name, drinking_water, usage_water,
// no_drinking, no_piped, wmi2, info_no_piped, drought_risk_65, drought_risk_66,
// ab_drought, agri_water, wmi6_2, drought_gistda, ab_flood, wmi6_1,
// flood_gistda, water_quality, wmi5, wmi7, landslide_risk, wmi8

const VILLAGES_ENRICHED = [
// อ.ท่าสองยาง - ต.ท่าสองยาง
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"ท่าสองยาง","หมู่บ้าน":"ท่าสองยาง","lat":17.571301,"lon":97.914605,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"2 ปีต่อครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"ต้องพัฒนา"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"ท่าสองยาง","หมู่บ้าน":"แม่ตื่น","lat":17.605801,"lon":97.898978,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาปานกลาง","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"พื้นที่เสี่ยงท่วมต่ำ","wmi5":"","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"ต้องพัฒนา"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"ท่าสองยาง","หมู่บ้าน":"มอกูตู้","lat":17.67035,"lon":97.861083,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาปานกลาง","usage_water":"มีปัญหาปานกลาง","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาน้อย","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"ต้องพัฒนา"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"ท่าสองยาง","หมู่บ้าน":"แม่เหว่ย","lat":17.710367,"lon":97.901274,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"ต้องพัฒนา"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"ท่าสองยาง","หมู่บ้าน":"ขุนแม่เหว่ย","lat":17.710449,"lon":97.89797,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"ดินไหล","plan_status":"ต้องพัฒนา"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"ท่าสองยาง","หมู่บ้าน":"แม่ละนา","lat":17.723694,"lon":97.856685,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาปานกลาง","usage_water":"มีปัญหาปานกลาง","no_drinking":"ไม่มีน้ำดื่ม","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"ต้องพัฒนา"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"ท่าสองยาง","หมู่บ้าน":"แม่อมยะ","lat":17.749527,"lon":97.872435,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0117","sub_basin_name":"แม่น้ำยวมตอนล่างส่วนที่4","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"ไม่มีน้ำดื่ม","no_piped":"ไม่มีประปา","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"ดินไหล","plan_status":"ต้องพัฒนา"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"ท่าสองยาง","หมู่บ้าน":"แม่จะวาง","lat":17.575734,"lon":97.959415,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาปานกลาง","no_drinking":"ไม่มีน้ำดื่ม","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"พื้นที่เสี่ยงท่วมต่ำ","wmi5":"","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"ต้องพัฒนา"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"ท่าสองยาง","หมู่บ้าน":"สวนอ้อย","lat":17.564156,"lon":97.913762,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหามาก","usage_water":"มีปัญหาน้อย","no_drinking":"ไม่มีน้ำดื่ม","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"2 ปีต่อครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"ต้องพัฒนา"},
// อ.ท่าสองยาง - ต.แม่ต้าน
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"แม่ต้าน","หมู่บ้าน":"แม่ต้าน/บ้านใหม่","lat":17.22711,"lon":98.225718,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"2 ปีต่อครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"มีปัญหาน้อย","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"มีประสิทธิภาพ"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"แม่ต้าน","หมู่บ้าน":"ลำร้อง","lat":17.231414,"lon":98.232898,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"มีปัญหาน้อย","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"น้ำป่าไหลหลาก","plan_status":"มีประสิทธิภาพ"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"แม่ต้าน","หมู่บ้าน":"ขุนห้วยแม่ขะโหมะ","lat":17.289863,"lon":98.308498,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"มีปัญหาน้อย","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่มและดินไหล","plan_status":"มีประสิทธิภาพ"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"แม่ต้าน","หมู่บ้าน":"แบรอทะ","lat":17.262366,"lon":98.306223,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาปานกลาง","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"มีปัญหาน้อย","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่มและดินไหล","plan_status":"มีประสิทธิภาพ"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"แม่ต้าน","หมู่บ้าน":"ห้วยปูแกง","lat":17.212719,"lon":98.307257,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"มีปัญหาปานกลาง","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"มีประสิทธิภาพ"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"แม่ต้าน","หมู่บ้าน":"ขุนห้วยแม่ต้าน","lat":17.272553,"lon":98.239163,"samsak":4,"risk":"เสี่ยงสูง","ews":"STN0662","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เสี่ยงปานกลาง","ab_drought":"","agri_water":"มีปัญหามาก","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"พื้นที่เสี่ยงท่วมต่ำ","wmi5":"มีปัญหาน้อย","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"มีประสิทธิภาพ"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"แม่ต้าน","หมู่บ้าน":"แม่โพ","lat":17.245423,"lon":98.27239,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาปานกลาง","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เสี่ยงปานกลาง","ab_drought":"","agri_water":"มีปัญหามาก","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"มีปัญหาน้อย","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"มีประสิทธิภาพ"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"แม่ต้าน","หมู่บ้าน":"บ้านแกละมื่อโจะ","lat":17.220887,"lon":98.292426,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"มีปัญหาน้อย","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"มีประสิทธิภาพ"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"แม่ต้าน","หมู่บ้าน":"ทุ่งถ้ำ","lat":17.269199,"lon":98.201856,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"ไม่มีประปาหมู่บ้าน","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"พื้นที่เสี่ยงท่วมปานกลาง","wmi5":"มีปัญหาน้อย","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"มีประสิทธิภาพ"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"แม่ต้าน","หมู่บ้าน":"ทุ่งนาสูง","lat":17.3233,"lon":98.281574,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาน้อย","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"พื้นที่เสี่ยงท่วมต่ำ","wmi5":"มีปัญหาน้อย","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่มและดินไหล","plan_status":"มีประสิทธิภาพ"}
];

// ── แผนปฏิบัติการด้านน้ำ ปี 67-69 ลุ่มน้ำสาละวิน (181 โครงการ) ──
const WATER_PLAN = [
// ── ด้านที่ 1: น้ำอุปโภคบริโภค ──
{seq:1,agency:"การประปาส่วนภูมิภาค",project:"งานวางท่อขยายเขตจำหน่ายน้ำ บ้านท่าข้าม (หย่อมบ้านใหม่ดอยคำ) หมู่ 1 ต.บ้านกาศ อ.แม่สะเรียง จ.แม่ฮ่องสอน",tambon:"บ้านกาศ",amphoe:"แม่สะเรียง",province:"แม่ฮ่องสอน",basin_sub:"แม่น้ำยวมตอนล่างส่วนที่ 1",lat:18.194319,lon:97.935037,budget:22.312,work_type:"ระบบประปา",plan_dim:"ด้านที่ 1",strategy:"1.2.4",budget_year:"ปี 67",allocated:1},
{seq:2,agency:"การประปาส่วนภูมิภาค",project:"งานวางท่อขยายเขตจำหน่ายน้ำ บริเวณโกดังข้าวนายเลิศ หมู่ 4 ต.แม่ตาว อ.แม่สอด จ.ตาก",tambon:"แม่ตาว",amphoe:"แม่สอด",province:"ตาก",basin_sub:"แม่น้ำเมยตอนบน",lat:16.680585,lon:98.559084,budget:1.521,work_type:"ระบบประปา",plan_dim:"ด้านที่ 1",strategy:"1.2.4",budget_year:"ปี 67",allocated:1},
{seq:3,agency:"การประปาส่วนภูมิภาค",project:"งานวางท่อขยายเขตจำหน่ายน้ำ ซอยข้างวัดชลประทานหัวฝาย หมู่ 2 ต.พระธาตุผาแดง อ.แม่สอด จ.ตาก",tambon:"พระธาตุผาแดง",amphoe:"แม่สอด",province:"ตาก",basin_sub:"แม่น้ำเมยตอนบน",lat:16.702613,lon:98.614259,budget:1.691,work_type:"ระบบประปา",plan_dim:"ด้านที่ 1",strategy:"1.2.4",budget_year:"ปี 67",allocated:1},
{seq:4,agency:"การประปาส่วนภูมิภาค",project:"งานปรับปรุงเพิ่มประสิทธิภาพระบบท่อจ่ายน้ำ การประปาส่วนภูมิภาคสาขาแม่สอด ต.แม่สอด อ.แม่สอด จ.ตาก",tambon:"แม่สอด",amphoe:"แม่สอด",province:"ตาก",basin_sub:"แม่น้ำเมยตอนบน",lat:16.709082,lon:98.553597,budget:30,work_type:"ระบบประปา",plan_dim:"ด้านที่ 1",strategy:"1.2.6",budget_year:"ปี 67",allocated:1},
// ── ด้านที่ 2: น้ำภาคการผลิต / ระบบกระจายน้ำสะอาด ──
{seq:5,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบกระจายน้ำสะอาดสนับสนุนโรงเรียนตำรวจตระเวนชายแดน ศ.สำเภา-ไพวรรณวรางกูร",tambon:"พะวอ",amphoe:"แม่สอด",province:"ตาก",basin_sub:"ห้วยแม่ละเมา",lat:16.69577,lon:98.77651,budget:0.4945,work_type:"ระบบกระจายน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.3.1",budget_year:"ปี 67",allocated:1},
{seq:6,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบกระจายน้ำสะอาดสนับสนุนโรงเรียนตำรวจตระเวนชายแดนท่านผู้หญิงทวีมณีนุตร",tambon:"พระธาตุผาแดง",amphoe:"แม่สอด",province:"ตาก",basin_sub:"แม่น้ำเมยตอนบน",lat:16.71801,lon:98.66334,budget:0.4944,work_type:"ระบบกระจายน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.3.1",budget_year:"ปี 67",allocated:1},
{seq:7,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบกระจายน้ำสะอาดสนับสนุนโรงเรียนตำรวจตระเวนชายแดนเทคนิคอาสา 1",tambon:"แม่อุสุ",amphoe:"ท่าสองยาง",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.32522,lon:98.18595,budget:0.4947,work_type:"ระบบกระจายน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.3.1",budget_year:"ปี 67",allocated:1},
{seq:8,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบกระจายน้ำสะอาดสนับสนุนโรงเรียนตำรวจตระเวนชายแดนกามาผาโด้",tambon:"แม่หละ",amphoe:"ท่าสองยาง",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.18105,lon:98.39194,budget:0.4939,work_type:"ระบบกระจายน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.3.1",budget_year:"ปี 67",allocated:1},
{seq:9,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบกระจายน้ำสะอาดสนับสนุนโรงเรียนตำรวจตระเวนชายแดนจุฬา-ธรรมศาสตร์ 3",tambon:"แม่หละ",amphoe:"ท่าสองยาง",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.11082,lon:98.33626,budget:0.4944,work_type:"ระบบกระจายน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.3.1",budget_year:"ปี 67",allocated:1},
{seq:10,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบกระจายน้ำสะอาดสนับสนุนโรงเรียนตำรวจตระเวนชายแดนท่านผู้หญิงประไพ ศิวะโกเศศ",tambon:"สบโขง",amphoe:"อมก๋อย",province:"เชียงใหม่",basin_sub:"น้ำแม่เงา",lat:17.64842,lon:98.10794,budget:0.4941,work_type:"ระบบกระจายน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.3.1",budget_year:"ปี 67",allocated:1},
{seq:11,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบกระจายน้ำสะอาดสนับสนุนศูนย์การเรียน ตชด.บ้านห้วยสลุง",tambon:"พระธาตุ",amphoe:"แม่ระมาด",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:16.98083,lon:98.60733,budget:0.4944,work_type:"ระบบกระจายน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.3.1",budget_year:"ปี 67",allocated:1},
{seq:12,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบกระจายน้ำสะอาดสนับสนุนศูนย์การเรียน ตชด.บ้านคะเนจือทะ",tambon:"แม่อุสุ",amphoe:"ท่าสองยาง",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.36856,lon:98.26309,budget:0.4942,work_type:"ระบบกระจายน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.3.1",budget_year:"ปี 67",allocated:1},
{seq:13,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบกระจายน้ำสะอาดสนับสนุนศูนย์การเรียน ตชด.บ้านตีนดอย",tambon:"แม่หละ",amphoe:"ท่าสองยาง",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.16054,lon:98.38027,budget:0.4945,work_type:"ระบบกระจายน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.3.1",budget_year:"ปี 67",allocated:1},
{seq:14,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบกระจายน้ำสะอาดสนับสนุนศูนย์การเรียน ตชด.บ้านแม่หละคี",tambon:"แม่หละ",amphoe:"ท่าสองยาง",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.17219,lon:98.45669,budget:0.4943,work_type:"ระบบกระจายน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.3.1",budget_year:"ปี 67",allocated:1},
{seq:15,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบกระจายน้ำสะอาดสนับสนุนศูนย์การเรียน ตชด.บ้านพอบือละคี",tambon:"แม่สอง",amphoe:"ท่าสองยาง",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.44937,lon:98.15933,budget:0.4947,work_type:"ระบบกระจายน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.3.1",budget_year:"ปี 67",allocated:1},
{seq:16,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบกระจายน้ำสะอาดสนับสนุนศูนย์การเรียน ตชด.บ้านเลโพเด",tambon:"แม่วะหลวง",amphoe:"ท่าสองยาง",province:"ตาก",basin_sub:"น้ำแม่เงา",lat:17.589,lon:98.08304,budget:0.4942,work_type:"ระบบกระจายน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.3.1",budget_year:"ปี 67",allocated:1},
{seq:17,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบกระจายน้ำสะอาดสนับสนุนศูนย์การเรียน ตชด.บ้านแม่อมยะ",tambon:"ท่าสองยาง",amphoe:"ท่าสองยาง",province:"ตาก",basin_sub:"แม่น้ำยวมตอนล่างส่วนที่ 4",lat:17.72997,lon:97.88061,budget:0.4935,work_type:"ระบบกระจายน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.3.1",budget_year:"ปี 67",allocated:1},
{seq:18,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบกระจายน้ำสะอาดสนับสนุนศูนย์การเรียน ตชด.บ้านแม่ละนา",tambon:"ท่าสองยาง",amphoe:"ท่าสองยาง",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.72318,lon:97.85416,budget:0.4939,work_type:"ระบบกระจายน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.3.1",budget_year:"ปี 67",allocated:1},
// ── ด้านที่ 2: ฝายชะลอน้ำ สปก. ──
{seq:19,agency:"สำนักงานการปฏิรูปที่ดินเพื่อเกษตรกรรม",project:"ฝายชะลอน้ำแบบชั่วคราว ปฏิรูปที่ดิน จ.ตาก 1 (วังผา)",tambon:"แม่จะเรา",amphoe:"แม่ระมาด",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:16.8416,lon:98.54,budget:0.052,work_type:"ฝาย",plan_dim:"ด้านที่ 2",strategy:"2.3.3",budget_year:"ปี 67",allocated:1},
{seq:20,agency:"สำนักงานการปฏิรูปที่ดินเพื่อเกษตรกรรม",project:"ฝายชะลอน้ำแบบชั่วคราว ปฏิรูปที่ดิน จ.ตาก 2 (วังผา)",tambon:"แม่จะเรา",amphoe:"แม่ระมาด",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:16.8404,lon:98.5374,budget:0.052,work_type:"ฝาย",plan_dim:"ด้านที่ 2",strategy:"2.3.3",budget_year:"ปี 67",allocated:1},
{seq:21,agency:"สำนักงานการปฏิรูปที่ดินเพื่อเกษตรกรรม",project:"ฝายชะลอน้ำแบบชั่วคราว ปฏิรูปที่ดิน จ.ตาก 3 (วังผา)",tambon:"แม่จะเรา",amphoe:"แม่ระมาด",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:16.884,lon:98.5571,budget:0.052,work_type:"ฝาย",plan_dim:"ด้านที่ 2",strategy:"2.3.3",budget_year:"ปี 67",allocated:1},
{seq:22,agency:"สำนักงานการปฏิรูปที่ดินเพื่อเกษตรกรรม",project:"ฝายชะลอน้ำแบบชั่วคราว ปฏิรูปที่ดิน จ.ตาก 4 (เจดีย์โค๊ะ)",tambon:"มหาวัน",amphoe:"แม่สอด",province:"ตาก",basin_sub:"แม่น้ำเมยตอนบน",lat:16.5756,lon:98.6885,budget:0.052,work_type:"ฝาย",plan_dim:"ด้านที่ 2",strategy:"2.3.3",budget_year:"ปี 67",allocated:1},
{seq:23,agency:"สำนักงานการปฏิรูปที่ดินเพื่อเกษตรกรรม",project:"ฝายชะลอน้ำแบบชั่วคราว ปฏิรูปที่ดิน จ.ตาก 5 (เจดีย์โค๊ะ)",tambon:"มหาวัน",amphoe:"แม่สอด",province:"ตาก",basin_sub:"แม่น้ำเมยตอนบน",lat:16.5765,lon:98.6856,budget:0.052,work_type:"ฝาย",plan_dim:"ด้านที่ 2",strategy:"2.3.3",budget_year:"ปี 67",allocated:1},
{seq:24,agency:"สำนักงานการปฏิรูปที่ดินเพื่อเกษตรกรรม",project:"ฝายชะลอน้ำแบบชั่วคราว ปฏิรูปที่ดิน จ.ตาก 6 (เจดีย์โค๊ะ)",tambon:"มหาวัน",amphoe:"แม่สอด",province:"ตาก",basin_sub:"แม่น้ำเมยตอนบน",lat:16.5742,lon:98.6822,budget:0.052,work_type:"ฝาย",plan_dim:"ด้านที่ 2",strategy:"2.3.3",budget_year:"ปี 67",allocated:1},
{seq:25,agency:"สำนักงานการปฏิรูปที่ดินเพื่อเกษตรกรรม",project:"ฝายชะลอน้ำแบบชั่วคราว ปฏิรูปที่ดิน จ.แม่ฮ่องสอน 1 (ห้วยหลวง)",tambon:"บ้านกาศ",amphoe:"แม่สะเรียง",province:"แม่ฮ่องสอน",basin_sub:"แม่น้ำยวมตอนล่างส่วนที่ 1",lat:18.2277,lon:97.929,budget:0.06,work_type:"ฝาย",plan_dim:"ด้านที่ 2",strategy:"2.3.3",budget_year:"ปี 67",allocated:1},
{seq:26,agency:"สำนักงานการปฏิรูปที่ดินเพื่อเกษตรกรรม",project:"ฝายชะลอน้ำแบบชั่วคราว ปฏิรูปที่ดิน จ.แม่ฮ่องสอน 2 (ห้วยหลวง)",tambon:"บ้านกาศ",amphoe:"แม่สะเรียง",province:"แม่ฮ่องสอน",basin_sub:"แม่น้ำยวมตอนล่างส่วนที่ 1",lat:18.2277,lon:97.929,budget:0.06,work_type:"ฝาย",plan_dim:"ด้านที่ 2",strategy:"2.3.3",budget_year:"ปี 67",allocated:1},
{seq:27,agency:"สำนักงานการปฏิรูปที่ดินเพื่อเกษตรกรรม",project:"ฝายชะลอน้ำแบบชั่วคราว ปฏิรูปที่ดิน จ.แม่ฮ่องสอน 3 (ห้วยหลวง)",tambon:"บ้านกาศ",amphoe:"แม่สะเรียง",province:"แม่ฮ่องสอน",basin_sub:"แม่น้ำยวมตอนล่างส่วนที่ 1",lat:18.2277,lon:97.929,budget:0.06,work_type:"ฝาย",plan_dim:"ด้านที่ 2",strategy:"2.3.3",budget_year:"ปี 67",allocated:1},
{seq:28,agency:"สำนักงานการปฏิรูปที่ดินเพื่อเกษตรกรรม",project:"ฝายชะลอน้ำแบบชั่วคราว ปฏิรูปที่ดิน จ.แม่ฮ่องสอน 4 (หัวแม่สุรินทร์)",tambon:"แม่อูคอ",amphoe:"ขุนยวม",province:"แม่ฮ่องสอน",basin_sub:"น้ำแม่สุรินทร์",lat:18.9191,lon:98.094,budget:0.06,work_type:"ฝาย",plan_dim:"ด้านที่ 2",strategy:"2.3.3",budget_year:"ปี 67",allocated:1},
{seq:29,agency:"สำนักงานการปฏิรูปที่ดินเพื่อเกษตรกรรม",project:"ฝายชะลอน้ำแบบชั่วคราว ปฏิรูปที่ดิน จ.แม่ฮ่องสอน 5 (หัวแม่สุรินทร์)",tambon:"แม่อูคอ",amphoe:"ขุนยวม",province:"แม่ฮ่องสอน",basin_sub:"น้ำแม่สุรินทร์",lat:18.9191,lon:98.094,budget:0.06,work_type:"ฝาย",plan_dim:"ด้านที่ 2",strategy:"2.3.3",budget_year:"ปี 67",allocated:1},
// ── ด้านที่ 2: อ่างเก็บน้ำ ──
{seq:30,agency:"กรมชลประทาน",project:"อ่างเก็บน้ำห้วยผักปิ้ง",tambon:"ขุนยวม",amphoe:"ขุนยวม",province:"แม่ฮ่องสอน",basin_sub:"น้ำแม่สุรินทร์",lat:18.7891,lon:97.9405,budget:50,work_type:"อ่างเก็บน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.4.1",budget_year:"ปี 67",allocated:1},
// ── ด้านที่ 3: ป้องกันน้ำท่วม ──
{seq:31,agency:"กรมโยธาธิการและผังเมือง",project:"ก่อสร้างระบบระบายน้ำหลักเพื่อบรรเทาปัญหาน้ำท่วมพื้นที่ชุมชนแม่สอด ระยะที่ 2 อ.แม่สอด จ.ตาก",tambon:"แม่สอด",amphoe:"แม่สอด",province:"ตาก",basin_sub:"แม่น้ำเมยตอนบน",lat:16.71223,lon:98.59614,budget:126.225,work_type:"ระบบระบายน้ำ",plan_dim:"ด้านที่ 3",strategy:"3.2.1",budget_year:"ปี 67",allocated:1},
// ── ด้านที่ 4: อนุรักษ์ป่าต้นน้ำ / ฝายต้นน้ำ ──
{seq:32,agency:"กรมอุทยานแห่งชาติ สัตว์ป่า และพันธุ์พืช",project:"ฝายต้นน้ำแบบคอกหมู ขนาด 5 เมตร ต.คีรีราษฎร์ อ.พบพระ จ.ตาก",tambon:"คีรีราษฎร์",amphoe:"พบพระ",province:"ตาก",basin_sub:"ห้วยแม่ละเมา",lat:16.37039,lon:99.00279,budget:0.007,work_type:"ฝายต้นน้ำ",plan_dim:"ด้านที่ 4",strategy:"4.2.1",budget_year:"ปี 67",allocated:1},
{seq:33,agency:"กรมอุทยานแห่งชาติ สัตว์ป่า และพันธุ์พืช",project:"ปลูกหญ้าแฝกเพื่ออนุรักษ์ดินและน้ำ ต.เวียงเหนือ อ.ปาย จ.แม่ฮ่องสอน",tambon:"เวียงเหนือ",amphoe:"ปาย",province:"แม่ฮ่องสอน",basin_sub:"น้ำแม่ปายตอนบน",lat:19.38456,lon:98.55629,budget:0.165,work_type:"ฟื้นฟูป่า",plan_dim:"ด้านที่ 4",strategy:"4.2.1",budget_year:"ปี 67",allocated:1},
{seq:34,agency:"กรมอุทยานแห่งชาติ สัตว์ป่า และพันธุ์พืช",project:"ปลูกหญ้าแฝกเพื่ออนุรักษ์ดินและน้ำ ต.ห้วยปูลิง อ.เมืองแม่ฮ่องสอน จ.แม่ฮ่องสอน (1)",tambon:"ห้วยปูลิง",amphoe:"เมืองแม่ฮ่องสอน",province:"แม่ฮ่องสอน",basin_sub:"น้ำแม่สะมาด",lat:19.21270,lon:98.04260,budget:0.165,work_type:"ฟื้นฟูป่า",plan_dim:"ด้านที่ 4",strategy:"4.2.1",budget_year:"ปี 67",allocated:1},
{seq:35,agency:"กรมอุทยานแห่งชาติ สัตว์ป่า และพันธุ์พืช",project:"ปลูกหญ้าแฝกเพื่ออนุรักษ์ดินและน้ำ ต.ห้วยปูลิง อ.เมืองแม่ฮ่องสอน จ.แม่ฮ่องสอน (2)",tambon:"ห้วยปูลิง",amphoe:"เมืองแม่ฮ่องสอน",province:"แม่ฮ่องสอน",basin_sub:"น้ำแม่สะมาด",lat:19.21127,lon:98.04605,budget:0.165,work_type:"ฟื้นฟูป่า",plan_dim:"ด้านที่ 4",strategy:"4.2.1",budget_year:"ปี 67",allocated:1},
{seq:36,agency:"กรมอุทยานแห่งชาติ สัตว์ป่า และพันธุ์พืช",project:"ฝายต้นน้ำแบบคอกหมู ขนาด 4 เมตร ต.แม่ฮี้ อ.ปาย จ.แม่ฮ่องสอน (ชุดที่ 1-15)",tambon:"แม่ฮี้",amphoe:"ปาย",province:"แม่ฮ่องสอน",basin_sub:"น้ำแม่ปายตอนบน",lat:19.24328,lon:98.52579,budget:0.086,work_type:"ฝายต้นน้ำ",plan_dim:"ด้านที่ 4",strategy:"4.2.1",budget_year:"ปี 67",allocated:1},
// ── โครงการ ปี 67 เพิ่มเติม (สรุปรายอำเภอ) ──
{seq:37,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบประปาหมู่บ้าน อ.แม่สะเรียง จ.แม่ฮ่องสอน",tambon:"แม่สะเรียง",amphoe:"แม่สะเรียง",province:"แม่ฮ่องสอน",basin_sub:"แม่น้ำยวมตอนล่างส่วนที่ 1",lat:18.17,lon:97.93,budget:1.5,work_type:"ระบบประปา",plan_dim:"ด้านที่ 1",strategy:"1.1.1",budget_year:"ปี 67",allocated:1},
{seq:38,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบประปาหมู่บ้าน บ.แม่ลาน้อย อ.แม่ลาน้อย จ.แม่ฮ่องสอน",tambon:"แม่ลาน้อย",amphoe:"แม่ลาน้อย",province:"แม่ฮ่องสอน",basin_sub:"แม่น้ำยวมตอนล่างส่วนที่ 2",lat:18.03,lon:97.97,budget:1.2,work_type:"ระบบประปา",plan_dim:"ด้านที่ 1",strategy:"1.1.1",budget_year:"ปี 67",allocated:1},
{seq:39,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบประปาหมู่บ้าน อ.สบเมย จ.แม่ฮ่องสอน",tambon:"สบเมย",amphoe:"สบเมย",province:"แม่ฮ่องสอน",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.97,lon:97.77,budget:1.3,work_type:"ระบบประปา",plan_dim:"ด้านที่ 1",strategy:"1.1.1",budget_year:"ปี 67",allocated:1},
{seq:40,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบประปาหมู่บ้าน อ.ขุนยวม จ.แม่ฮ่องสอน",tambon:"ขุนยวม",amphoe:"ขุนยวม",province:"แม่ฮ่องสอน",basin_sub:"น้ำแม่สุรินทร์",lat:18.82,lon:97.96,budget:1.1,work_type:"ระบบประปา",plan_dim:"ด้านที่ 1",strategy:"1.1.1",budget_year:"ปี 67",allocated:1},
{seq:41,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบประปาหมู่บ้าน อ.ปางมะผ้า จ.แม่ฮ่องสอน",tambon:"ปางมะผ้า",amphoe:"ปางมะผ้า",province:"แม่ฮ่องสอน",basin_sub:"น้ำแม่ปายตอนบน",lat:19.52,lon:98.28,budget:0.9,work_type:"ระบบประปา",plan_dim:"ด้านที่ 1",strategy:"1.1.1",budget_year:"ปี 67",allocated:1},
{seq:42,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบประปาหมู่บ้าน อ.ปาย จ.แม่ฮ่องสอน",tambon:"เวียงใต้",amphoe:"ปาย",province:"แม่ฮ่องสอน",basin_sub:"น้ำแม่ปายตอนบน",lat:19.36,lon:98.44,budget:1.0,work_type:"ระบบประปา",plan_dim:"ด้านที่ 1",strategy:"1.1.1",budget_year:"ปี 67",allocated:1},
{seq:43,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบประปาหมู่บ้าน อ.เมืองแม่ฮ่องสอน",tambon:"จองคำ",amphoe:"เมืองแม่ฮ่องสอน",province:"แม่ฮ่องสอน",basin_sub:"น้ำแม่สะมาด",lat:19.30,lon:97.96,budget:1.0,work_type:"ระบบประปา",plan_dim:"ด้านที่ 1",strategy:"1.1.1",budget_year:"ปี 67",allocated:1},
// ── ปี 68 ──
{seq:44,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบประปาหมู่บ้าน อ.ท่าสองยาง จ.ตาก (ปี 68)",tambon:"ท่าสองยาง",amphoe:"ท่าสองยาง",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.57,lon:97.91,budget:1.5,work_type:"ระบบประปา",plan_dim:"ด้านที่ 1",strategy:"1.1.1",budget_year:"ปี 68",allocated:0},
{seq:45,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบประปาหมู่บ้าน อ.แม่ระมาด จ.ตาก (ปี 68)",tambon:"แม่จะเรา",amphoe:"แม่ระมาด",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:16.98,lon:98.52,budget:1.2,work_type:"ระบบประปา",plan_dim:"ด้านที่ 1",strategy:"1.1.1",budget_year:"ปี 68",allocated:0},
{seq:46,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบประปาหมู่บ้าน อ.พบพระ จ.ตาก (ปี 68)",tambon:"คีรีราษฎร์",amphoe:"พบพระ",province:"ตาก",basin_sub:"ห้วยแม่ละเมา",lat:16.37,lon:98.82,budget:1.0,work_type:"ระบบประปา",plan_dim:"ด้านที่ 1",strategy:"1.1.1",budget_year:"ปี 68",allocated:0},
{seq:47,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบกระจายน้ำสะอาด อ.ท่าสองยาง จ.ตาก (ปี 68)",tambon:"แม่สอง",amphoe:"ท่าสองยาง",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.45,lon:98.16,budget:0.49,work_type:"ระบบกระจายน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.3.1",budget_year:"ปี 68",allocated:0},
{seq:48,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบกระจายน้ำสะอาด อ.แม่ระมาด จ.ตาก (ปี 68)",tambon:"พระธาตุ",amphoe:"แม่ระมาด",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:16.98,lon:98.61,budget:0.49,work_type:"ระบบกระจายน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.3.1",budget_year:"ปี 68",allocated:0},
{seq:49,agency:"กรมชลประทาน",project:"ฝายทดน้ำห้วยแม่ระมาด อ.แม่ระมาด จ.ตาก (ปี 68)",tambon:"แม่จะเรา",amphoe:"แม่ระมาด",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:16.87,lon:98.57,budget:15.0,work_type:"ฝาย",plan_dim:"ด้านที่ 2",strategy:"2.4.1",budget_year:"ปี 68",allocated:0},
{seq:50,agency:"กรมชลประทาน",project:"ระบบส่งน้ำฝายห้วยแม่กลอง อ.ท่าสองยาง จ.ตาก (ปี 68)",tambon:"แม่หละ",amphoe:"ท่าสองยาง",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.18,lon:98.38,budget:12.0,work_type:"ระบบส่งน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.4.1",budget_year:"ปี 68",allocated:0},
{seq:51,agency:"กรมโยธาธิการและผังเมือง",project:"ก่อสร้างเขื่อนป้องกันตลิ่ง แม่น้ำเมย อ.แม่สอด จ.ตาก (ปี 68)",tambon:"แม่สอด",amphoe:"แม่สอด",province:"ตาก",basin_sub:"แม่น้ำเมยตอนบน",lat:16.71,lon:98.58,budget:45.0,work_type:"ป้องกันตลิ่ง",plan_dim:"ด้านที่ 3",strategy:"3.2.2",budget_year:"ปี 68",allocated:0},
{seq:52,agency:"กรมโยธาธิการและผังเมือง",project:"ก่อสร้างเขื่อนป้องกันตลิ่ง แม่น้ำยวม อ.แม่สะเรียง จ.แม่ฮ่องสอน (ปี 68)",tambon:"แม่สะเรียง",amphoe:"แม่สะเรียง",province:"แม่ฮ่องสอน",basin_sub:"แม่น้ำยวมตอนล่างส่วนที่ 1",lat:18.17,lon:97.93,budget:38.0,work_type:"ป้องกันตลิ่ง",plan_dim:"ด้านที่ 3",strategy:"3.2.2",budget_year:"ปี 68",allocated:0},
{seq:53,agency:"กรมทรัพยากรน้ำ",project:"ฝายชะลอน้ำ อ.สบเมย จ.แม่ฮ่องสอน (ปี 68 กลุ่ม 1)",tambon:"สบเมย",amphoe:"สบเมย",province:"แม่ฮ่องสอน",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.97,lon:97.77,budget:2.5,work_type:"ฝาย",plan_dim:"ด้านที่ 2",strategy:"2.3.3",budget_year:"ปี 68",allocated:0},
{seq:54,agency:"กรมทรัพยากรน้ำ",project:"ฝายชะลอน้ำ อ.สบเมย จ.แม่ฮ่องสอน (ปี 68 กลุ่ม 2)",tambon:"แม่คะตวน",amphoe:"สบเมย",province:"แม่ฮ่องสอน",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.85,lon:97.84,budget:2.5,work_type:"ฝาย",plan_dim:"ด้านที่ 2",strategy:"2.3.3",budget_year:"ปี 68",allocated:0},
{seq:55,agency:"กรมทรัพยากรน้ำ",project:"ระบบเตือนภัยน้ำท่วม EWS อ.ท่าสองยาง จ.ตาก (ปี 68)",tambon:"แม่ต้าน",amphoe:"ท่าสองยาง",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.25,lon:98.27,budget:3.5,work_type:"ระบบเตือนภัย",plan_dim:"ด้านที่ 3",strategy:"3.4.1",budget_year:"ปี 68",allocated:0},
{seq:56,agency:"กรมทรัพยากรน้ำ",project:"ระบบเตือนภัยน้ำท่วม EWS อ.แม่ระมาด จ.ตาก (ปี 68)",tambon:"แม่จะเรา",amphoe:"แม่ระมาด",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:16.90,lon:98.52,budget:3.5,work_type:"ระบบเตือนภัย",plan_dim:"ด้านที่ 3",strategy:"3.4.1",budget_year:"ปี 68",allocated:0},
{seq:57,agency:"กรมอุทยานแห่งชาติ สัตว์ป่า และพันธุ์พืช",project:"ฟื้นฟูป่าต้นน้ำเสื่อมโทรม เขตอุทยานแห่งชาติดอยอินทนนท์ (สาละวิน) ปี 68",tambon:"แม่วะหลวง",amphoe:"ท่าสองยาง",province:"ตาก",basin_sub:"น้ำแม่เงา",lat:17.59,lon:98.08,budget:5.0,work_type:"ฟื้นฟูป่า",plan_dim:"ด้านที่ 4",strategy:"4.1.1",budget_year:"ปี 68",allocated:0},
{seq:58,agency:"กรมทรัพยากรน้ำบาดาล",project:"สำรวจและพัฒนาน้ำบาดาล อ.แม่สะเรียง จ.แม่ฮ่องสอน (ปี 68)",tambon:"บ้านกาศ",amphoe:"แม่สะเรียง",province:"แม่ฮ่องสอน",basin_sub:"แม่น้ำยวมตอนล่างส่วนที่ 1",lat:18.18,lon:97.92,budget:2.8,work_type:"น้ำบาดาล",plan_dim:"ด้านที่ 1",strategy:"1.3.2",budget_year:"ปี 68",allocated:0},
{seq:59,agency:"กรมทรัพยากรน้ำบาดาล",project:"สำรวจและพัฒนาน้ำบาดาล อ.เมืองแม่ฮ่องสอน (ปี 68)",tambon:"จองคำ",amphoe:"เมืองแม่ฮ่องสอน",province:"แม่ฮ่องสอน",basin_sub:"น้ำแม่สะมาด",lat:19.30,lon:97.96,budget:2.5,work_type:"น้ำบาดาล",plan_dim:"ด้านที่ 1",strategy:"1.3.2",budget_year:"ปี 68",allocated:0},
{seq:60,agency:"กรมชลประทาน",project:"ก่อสร้างฝายห้วยแม่ต้าน อ.ท่าสองยาง จ.ตาก (ปี 68)",tambon:"แม่ต้าน",amphoe:"ท่าสองยาง",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.26,lon:98.23,budget:18.0,work_type:"ฝาย",plan_dim:"ด้านที่ 2",strategy:"2.4.1",budget_year:"ปี 68",allocated:0},
{seq:61,agency:"กรมชลประทาน",project:"อ่างเก็บน้ำห้วยแม่หละ อ.ท่าสองยาง จ.ตาก (ปี 68)",tambon:"แม่หละ",amphoe:"ท่าสองยาง",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.12,lon:98.40,budget:35.0,work_type:"อ่างเก็บน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.4.1",budget_year:"ปี 68",allocated:0},
{seq:62,agency:"กรมชลประทาน",project:"อ่างเก็บน้ำห้วยแม่สะเรียง จ.แม่ฮ่องสอน (ปี 68)",tambon:"แม่สะเรียง",amphoe:"แม่สะเรียง",province:"แม่ฮ่องสอน",basin_sub:"แม่น้ำยวมตอนล่างส่วนที่ 1",lat:18.15,lon:97.95,budget:42.0,work_type:"อ่างเก็บน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.4.1",budget_year:"ปี 68",allocated:0},
{seq:63,agency:"กรมทรัพยากรน้ำ",project:"ระบบประปาหมู่บ้าน อ.สบเมย จ.แม่ฮ่องสอน (ปี 68)",tambon:"แม่คะตวน",amphoe:"สบเมย",province:"แม่ฮ่องสอน",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.82,lon:97.88,budget:1.4,work_type:"ระบบประปา",plan_dim:"ด้านที่ 1",strategy:"1.1.1",budget_year:"ปี 68",allocated:0},
{seq:64,agency:"กรมทรัพยากรน้ำ",project:"ระบบประปาหมู่บ้าน อ.แม่ลาน้อย จ.แม่ฮ่องสอน (ปี 68)",tambon:"แม่ลาน้อย",amphoe:"แม่ลาน้อย",province:"แม่ฮ่องสอน",basin_sub:"แม่น้ำยวมตอนล่างส่วนที่ 2",lat:18.03,lon:97.97,budget:1.3,work_type:"ระบบประปา",plan_dim:"ด้านที่ 1",strategy:"1.1.1",budget_year:"ปี 68",allocated:0},
{seq:65,agency:"กรมชลประทาน",project:"ระบบส่งน้ำฝายห้วยแม่ขาน อ.แม่สะเรียง จ.แม่ฮ่องสอน (ปี 68)",tambon:"บ้านกาศ",amphoe:"แม่สะเรียง",province:"แม่ฮ่องสอน",basin_sub:"แม่น้ำยวมตอนล่างส่วนที่ 1",lat:18.19,lon:97.94,budget:8.0,work_type:"ระบบส่งน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.2.1",budget_year:"ปี 68",allocated:0},
// ── ปี 69 ──
{seq:66,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบกระจายน้ำสะอาด อ.พบพระ จ.ตาก (ปี 69)",tambon:"คีรีราษฎร์",amphoe:"พบพระ",province:"ตาก",basin_sub:"ห้วยแม่ละเมา",lat:16.33,lon:98.82,budget:0.49,work_type:"ระบบกระจายน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.3.1",budget_year:"ปี 69",allocated:0},
{seq:67,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบกระจายน้ำสะอาด อ.แม่สอด จ.ตาก (ปี 69)",tambon:"พะวอ",amphoe:"แม่สอด",province:"ตาก",basin_sub:"ห้วยแม่ละเมา",lat:16.70,lon:98.78,budget:0.49,work_type:"ระบบกระจายน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.3.1",budget_year:"ปี 69",allocated:0},
{seq:68,agency:"กรมชลประทาน",project:"อ่างเก็บน้ำห้วยแม่สะงา อ.แม่ลาน้อย จ.แม่ฮ่องสอน (ปี 69)",tambon:"แม่ลาน้อย",amphoe:"แม่ลาน้อย",province:"แม่ฮ่องสอน",basin_sub:"แม่น้ำยวมตอนล่างส่วนที่ 2",lat:18.04,lon:97.98,budget:55.0,work_type:"อ่างเก็บน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.4.1",budget_year:"ปี 69",allocated:0},
{seq:69,agency:"กรมชลประทาน",project:"อ่างเก็บน้ำห้วยแม่ปาย อ.ปาย จ.แม่ฮ่องสอน (ปี 69)",tambon:"แม่ฮี้",amphoe:"ปาย",province:"แม่ฮ่องสอน",basin_sub:"น้ำแม่ปายตอนบน",lat:19.34,lon:98.43,budget:48.0,work_type:"อ่างเก็บน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.4.1",budget_year:"ปี 69",allocated:0},
{seq:70,agency:"กรมโยธาธิการและผังเมือง",project:"ก่อสร้างระบบป้องกันน้ำท่วมชุมชน อ.ขุนยวม จ.แม่ฮ่องสอน (ปี 69)",tambon:"ขุนยวม",amphoe:"ขุนยวม",province:"แม่ฮ่องสอน",basin_sub:"น้ำแม่สุรินทร์",lat:18.82,lon:97.96,budget:32.0,work_type:"ป้องกันน้ำท่วม",plan_dim:"ด้านที่ 3",strategy:"3.2.1",budget_year:"ปี 69",allocated:0},
{seq:71,agency:"กรมโยธาธิการและผังเมือง",project:"ก่อสร้างระบบป้องกันน้ำท่วมชุมชน อ.ปาย จ.แม่ฮ่องสอน (ปี 69)",tambon:"เวียงใต้",amphoe:"ปาย",province:"แม่ฮ่องสอน",basin_sub:"น้ำแม่ปายตอนบน",lat:19.36,lon:98.44,budget:28.0,work_type:"ป้องกันน้ำท่วม",plan_dim:"ด้านที่ 3",strategy:"3.2.1",budget_year:"ปี 69",allocated:0},
{seq:72,agency:"กรมชลประทาน",project:"อ่างเก็บน้ำห้วยแม่วะ อ.แม่ระมาด จ.ตาก (ปี 69)",tambon:"แม่จะเรา",amphoe:"แม่ระมาด",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:16.86,lon:98.54,budget:65.0,work_type:"อ่างเก็บน้ำ",plan_dim:"ด้านที่ 2",strategy:"2.4.1",budget_year:"ปี 69",allocated:0},
{seq:73,agency:"กรมทรัพยากรน้ำ",project:"ก่อสร้างระบบประปาหมู่บ้าน อ.ท่าสองยาง จ.ตาก (ปี 69)",tambon:"แม่ต้าน",amphoe:"ท่าสองยาง",province:"ตาก",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.25,lon:98.22,budget:1.8,work_type:"ระบบประปา",plan_dim:"ด้านที่ 1",strategy:"1.1.1",budget_year:"ปี 69",allocated:0},
{seq:74,agency:"กรมทรัพยากรน้ำ",project:"ระบบเตือนภัยน้ำท่วม EWS อ.สบเมย จ.แม่ฮ่องสอน (ปี 69)",tambon:"สบเมย",amphoe:"สบเมย",province:"แม่ฮ่องสอน",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.97,lon:97.77,budget:3.8,work_type:"ระบบเตือนภัย",plan_dim:"ด้านที่ 3",strategy:"3.4.1",budget_year:"ปี 69",allocated:0},
{seq:75,agency:"กรมอุทยานแห่งชาติ สัตว์ป่า และพันธุ์พืช",project:"ฟื้นฟูป่าต้นน้ำเสื่อมโทรม เขตรักษาพันธุ์สัตว์ป่าสาละวิน (ปี 69)",tambon:"สบเมย",amphoe:"สบเมย",province:"แม่ฮ่องสอน",basin_sub:"แม่น้ำเมยตอนล่าง",lat:17.88,lon:97.72,budget:8.0,work_type:"ฟื้นฟูป่า",plan_dim:"ด้านที่ 4",strategy:"4.1.1",budget_year:"ปี 69",allocated:0},
];

// ── Cross-reference: จับคู่โครงการกับหมู่บ้านท่วม/แล้ง ──
function matchPlanToVillages(planArr, villageArr) {
  return planArr.map(p => {
    // Match by amphoe+tambon first, then by lat/lon proximity (~0.08 deg)
    const byLocation = villageArr.filter(v =>
      (v['อำเภอ'] === p.amphoe && v['ตำบล'] === p.tambon) ||
      (Math.abs(v.lat - p.lat) < 0.08 && Math.abs(v.lon - p.lon) < 0.08)
    );
    const floodVils = byLocation.filter(v => v.type === 'flood');
    const droughtVils = byLocation.filter(v => v.type === 'drought');
    const names = [...new Set(byLocation.map(v => v['หมู่บ้าน']))].slice(0, 5);
    return {
      ...p,
      hit_flood: floodVils.length > 0,
      hit_drought: droughtVils.length > 0,
      matched_count: byLocation.length,
      matched_villages: names
    };
  });
}

const SUB_BASINS = [
  {code:"0122",name:"แม่น้ำเมยตอนล่าง",main:"สาละวิน"},
  {code:"0121",name:"ห้วยแม่ละเมา",main:"สาละวิน"},
  {code:"0120",name:"แม่น้ำเมยตอนบน",main:"สาละวิน"},
  {code:"0117",name:"แม่น้ำยวมตอนล่างส่วนที่4",main:"สาละวิน"},
  {code:"0116",name:"น้ำแม่เงา",main:"สาละวิน"}
];

// ── Helper: Merge enriched data into VILLAGES ──
function mergeEnrichedData(baseVillages, enrichedData) {
  return baseVillages.map(v => {
    const e = enrichedData.find(ev =>
      ev['จังหวัด'] === v['จังหวัด'] &&
      ev['อำเภอ'] === v['อำเภอ'] &&
      ev['ตำบล'] === v['ตำบล'] &&
      ev['หมู่บ้าน'] === v['หมู่บ้าน'] &&
      ev.type === v.type
    );
    if (e) {
      return {...v, ...e};
    }
    // For villages without enriched data, add empty fields
    return {
      ...v,
      sub_basin_code: v.sub_basin_code || '',
      sub_basin_name: v.sub_basin_name || '',
      drinking_water: v.drinking_water || '',
      usage_water: v.usage_water || '',
      no_drinking: v.no_drinking || '',
      no_piped: v.no_piped || '',
      wmi2: v.wmi2 || '',
      info_no_piped: v.info_no_piped || '',
      drought_risk_65: v.drought_risk_65 || '',
      drought_risk_66: v.drought_risk_66 || '',
      ab_drought: v.ab_drought || '',
      agri_water: v.agri_water || '',
      wmi6_2: v.wmi6_2 || '',
      drought_gistda: v.drought_gistda || '',
      ab_flood: v.ab_flood || '',
      wmi6_1: v.wmi6_1 || '',
      flood_gistda: v.flood_gistda || '',
      water_quality: v.water_quality || '',
      wmi5: v.wmi5 || '',
      wmi7: v.wmi7 || '',
      landslide_risk: v.landslide_risk || '',
      wmi8: v.wmi8 || '',
      plan_status: v.plan_status || ''
    };
  });
}
