// ── ข้อมูลรายหมู่บ้านเพิ่มเติมจาก Excel ลุ่มน้ำสาละวิน ──
// เพิ่มฟิลด์: sub_basin_code, sub_basin_name, drinking_water, usage_water,
// no_drinking, no_piped, wmi2, info_no_piped, drought_risk_65, drought_risk_66,
// ab_drought, agri_water, wmi6_2, drought_gistda, ab_flood, wmi6_1,
// flood_gistda, water_quality, wmi5, wmi7, landslide_risk, wmi8

const VILLAGES_ENRICHED = [
// อ.ท่าสองยาง - ต.ท่าสองยาง
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"ท่าสองยาง","หมู่บ้าน":"ท่าสองยาง","lat":17.571301,"lon":97.914605,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"2 ปีต่อครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"ต้องพัฒนา"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"ท่าสองยาง","หมู่บ้าน":"แม่ตื่น","lat":17.605801,"lon":97.898978,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาปานกลาง","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"พื้นที่เสี่ยงท่วมต่ำ","wmi5":"","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"ต้องพัฒนา"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"ท่าสองยาง","หมู่บ้าน":"มอกูตู้","lat":17.67035,"lon":97.861083,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาปานกลาง","usage_water":"มีปัญหาปานกลาง","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาน้อย","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"ต้องพัฒนา"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"ท่าสองยาง","หมู่บ้าน":"แม่เหว่ย","lat":17.710367,"lon":97.901274,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"ต้องพัฒนา"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"ท่าสองยาง","หมู่บ้าน":"ขุนแม่เหว่ย","lat":17.710449,"lon":97.89797,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"ดินไหล","plan_status":"ต้องพัฒนา"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"ท่าสองยาง","หมู่บ้าน":"แม่ละนา","lat":17.723694,"lon":97.856685,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาปานกลาง","usage_water":"มีปัญหาปานกลาง","no_drinking":"ไม่มีน้ำดื่ม","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"ต้องพัฒนา"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"ท่าสองยาง","หมู่บ้าน":"แม่อมยะ","lat":17.749527,"lon":97.872435,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0117","sub_basin_name":"แม่น้ำยวมตอนล่างส่วนที่4","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"ไม่มีน้ำดื่ม","no_piped":"ไม่มีประปา","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"ดินไหล","plan_status":"ต้องพัฒนา"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"ท่าสองยาง","หมู่บ้าน":"แม่จะวาง","lat":17.575734,"lon":97.959415,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาปานกลาง","no_drinking":"ไม่มีน้ำดื่ม","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"พื้นที่เสี่ยงท่วมต่ำ","wmi5":"","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"ต้องพัฒนา"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"ท่าสองยาง","หมู่บ้าน":"สวนอ้อย","lat":17.564156,"lon":97.913762,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหามาก","usage_water":"มีปัญหาน้อย","no_drinking":"ไม่มีน้ำดื่ม","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"2 ปีต่อครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"ต้องพัฒนา"},
// อ.ท่าสองยาง - ต.แม่ต้าน
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"แม่ต้าน","หมู่บ้าน":"แม่ต้าน/บ้านใหม่","lat":17.22711,"lon":98.225718,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"2 ปีต่อครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"มีปัญหาน้อย","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"มีประสิทธิภาพ"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"แม่ต้าน","หมู่บ้าน":"ลำร้อง","lat":17.231414,"lon":98.232898,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"มีปัญหาน้อย","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"น้ำป่าไหลหลาก","plan_status":"มีประสิทธิภาพ"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"แม่ต้าน","หมู่บ้าน":"ขุนห้วยแม่ขะโหมะ","lat":17.289863,"lon":98.308498,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"มีปัญหาน้อย","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่มและดินไหล","plan_status":"มีประสิทธิภาพ"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"แม่ต้าน","หมู่บ้าน":"แบรอทะ","lat":17.262366,"lon":98.306223,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาปานกลาง","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"มีปัญหาน้อย","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่มและดินไหล","plan_status":"มีประสิทธิภาพ"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"แม่ต้าน","หมู่บ้าน":"ห้วยปูแกง","lat":17.212719,"lon":98.307257,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"มีปัญหาปานกลาง","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"มีประสิทธิภาพ"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"แม่ต้าน","หมู่บ้าน":"ขุนห้วยแม่ต้าน","lat":17.272553,"lon":98.239163,"samsak":4,"risk":"เสี่ยงสูง","ews":"STN0662","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เสี่ยงปานกลาง","ab_drought":"","agri_water":"มีปัญหามาก","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"พื้นที่เสี่ยงท่วมต่ำ","wmi5":"มีปัญหาน้อย","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"มีประสิทธิภาพ"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"แม่ต้าน","หมู่บ้าน":"แม่โพ","lat":17.245423,"lon":98.27239,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาปานกลาง","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เสี่ยงปานกลาง","ab_drought":"","agri_water":"มีปัญหามาก","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"มีปัญหาน้อย","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"มีประสิทธิภาพ"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"แม่ต้าน","หมู่บ้าน":"บ้านแกละมื่อโจะ","lat":17.220887,"lon":98.292426,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"ที่ลาดชันเชิงซ้อน","wmi5":"มีปัญหาน้อย","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"มีประสิทธิภาพ"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"แม่ต้าน","หมู่บ้าน":"ทุ่งถ้ำ","lat":17.269199,"lon":98.201856,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"ไม่มีประปาหมู่บ้าน","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาปานกลาง","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"พื้นที่เสี่ยงท่วมปานกลาง","wmi5":"มีปัญหาน้อย","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่ม น้ำป่าไหลหลากและดินไหล","plan_status":"มีประสิทธิภาพ"},
{"จังหวัด":"ตาก","อำเภอ":"ท่าสองยาง","ตำบล":"แม่ต้าน","หมู่บ้าน":"ทุ่งนาสูง","lat":17.3233,"lon":98.281574,"samsak":4,"risk":"เสี่ยงสูง","ews":"ไม่ครอบคลุม","type":"flood","sub_basin_code":"0122","sub_basin_name":"แม่น้ำเมยตอนล่าง","drinking_water":"มีปัญหาน้อย","usage_water":"มีปัญหาน้อย","no_drinking":"","no_piped":"","wmi2":"มีประสิทธิภาพ","info_no_piped":"","drought_risk_65":"เสี่ยงมาก","drought_risk_66":"พื้นที่เฝ้าระวัง","ab_drought":"","agri_water":"มีปัญหาน้อย","wmi6_2":"ต้นแบบ","drought_gistda":"","ab_flood":"ระดับต่ำ","wmi6_1":"","flood_gistda":"ปีละ 1 ครั้ง","water_quality":"พื้นที่เสี่ยงท่วมต่ำ","wmi5":"มีปัญหาน้อย","wmi7":"ต้นแบบ","landslide_risk":"มีประสิทธิภาพ","wmi8":"แผ่นดินถล่มและดินไหล","plan_status":"มีประสิทธิภาพ"}
];

// ── ข้อมูลลุ่มน้ำย่อย ──
const SUB_BASINS = [
  {code:"0122",name:"แม่น้ำเมยตอนล่าง",main:"สาละวิน"},
  {code:"0121",name:"ห้วยแม่ละเมา",main:"สาละวิน"},
  {code:"0120",name:"แม่น้ำเมยตอนบน",main:"สาละวิน"},
  {code:"0117",name:"แม่น้ำยวมตอนล่างส่วนที่4",main:"สาละวิน"},
  {code:"0116",name:"น้ำแม่เงา",main:"สาละวิน"}
];

// ── Helper: Merge enriched data into VILLAGES ──
function mergeEnrichedData(baseVillages, enrichedData) {
  return baseVillages.map(v => {
    const e = enrichedData.find(ev =>
      ev['จังหวัด'] === v['จังหวัด'] &&
      ev['อำเภอ'] === v['อำเภอ'] &&
      ev['ตำบล'] === v['ตำบล'] &&
      ev['หมู่บ้าน'] === v['หมู่บ้าน'] &&
      ev.type === v.type
    );
    if (e) {
      return {...v, ...e};
    }
    // For villages without enriched data, add empty fields
    return {
      ...v,
      sub_basin_code: v.sub_basin_code || '',
      sub_basin_name: v.sub_basin_name || '',
      drinking_water: v.drinking_water || '',
      usage_water: v.usage_water || '',
      no_drinking: v.no_drinking || '',
      no_piped: v.no_piped || '',
      wmi2: v.wmi2 || '',
      info_no_piped: v.info_no_piped || '',
      drought_risk_65: v.drought_risk_65 || '',
      drought_risk_66: v.drought_risk_66 || '',
      ab_drought: v.ab_drought || '',
      agri_water: v.agri_water || '',
      wmi6_2: v.wmi6_2 || '',
      drought_gistda: v.drought_gistda || '',
      ab_flood: v.ab_flood || '',
      wmi6_1: v.wmi6_1 || '',
      flood_gistda: v.flood_gistda || '',
      water_quality: v.water_quality || '',
      wmi5: v.wmi5 || '',
      wmi7: v.wmi7 || '',
      landslide_risk: v.landslide_risk || '',
      wmi8: v.wmi8 || '',
      plan_status: v.plan_status || ''
    };
  });
}
